// List of JS-callable commands. Keep in sync with `commands` module and
// with the permission manifests under `permissions/autogenerated/commands/`.
const COMMANDS: &[&str] = &["init", "show_rewarded", "show_interstitial", "launch_test_suite"];

// (output xcframework name, zip URL, wrapper dir inside zip)
//
// SPM binary targets fetched by URL silently fail to expose their Swift
// module to consuming targets when the upstream zip nests the xcframework
// inside a wrapper directory (e.g. `IronSource/IronSource.xcframework`).
// Tauri invokes `swift build` from the CLI via swift-rs and the resulting
// "no such module 'IronSource'" only surfaces at compile time. Workaround:
// pre-download and extract to a stable local path, then declare the binary
// target with `path:` in Package.swift — local binary targets resolve
// correctly regardless of nesting.
//
// See https://github.com/swiftlang/swift-package-manager/issues/5723.
#[cfg(target_os = "macos")]
const IOS_XCFRAMEWORKS: &[(&str, &str, &str)] = &[
    (
        "IronSource.xcframework",
        "https://raw.githubusercontent.com/ironsource-mobile/iOS-sdk/master/9.4.0/IronSource9.4.0.zip",
        "IronSource",
    ),
    (
        "ISAdMobAdapter.xcframework",
        "https://raw.githubusercontent.com/ironsource-mobile/iOS-adapters/master/admob-adapter/5.7.0/ISAdMobAdapter5.7.0.zip",
        "ISAdMobAdapter",
    ),
];

fn main() {
    #[cfg(target_os = "macos")]
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("ios") {
        prepare_ios_xcframeworks();
    }

    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}

#[cfg(target_os = "macos")]
fn prepare_ios_xcframeworks() {
    use std::path::PathBuf;
    use std::process::Command;

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let frameworks_dir = manifest_dir.join("ios").join("Frameworks");
    std::fs::create_dir_all(&frameworks_dir).expect("create Frameworks dir");

    // The xcframeworks contain ios-arm64 (device) and ios-arm64_x86_64-simulator
    // slices. iOS CI builds for device only (TestFlight/App Store), so we wire
    // the linker at the device slice. Add a second pair of `-F` / `-l` lines
    // here keyed off CARGO_CFG_TARGET_ABI if simulator builds are needed.
    let slice = "ios-arm64";

    for (xcframework_name, url, wrapper) in IOS_XCFRAMEWORKS {
        let target = frameworks_dir.join(xcframework_name);
        if !target.exists() {
            let tmp_zip = std::env::temp_dir().join(format!("{xcframework_name}.zip"));
            let tmp_extract = std::env::temp_dir().join(format!("{xcframework_name}.extract"));
            let _ = std::fs::remove_file(&tmp_zip);
            let _ = std::fs::remove_dir_all(&tmp_extract);
            std::fs::create_dir_all(&tmp_extract).expect("create temp extract dir");

            let curl_status = Command::new("curl")
                .args(["-sSLf", "-o"])
                .arg(&tmp_zip)
                .arg(url)
                .status()
                .expect("invoke curl");
            assert!(curl_status.success(), "curl failed for {url}");

            let unzip_status = Command::new("unzip")
                .arg("-q")
                .arg(&tmp_zip)
                .arg("-d")
                .arg(&tmp_extract)
                .status()
                .expect("invoke unzip");
            assert!(unzip_status.success(), "unzip failed for {xcframework_name}");

            let extracted = tmp_extract.join(wrapper).join(xcframework_name);
            std::fs::rename(&extracted, &target)
                .unwrap_or_else(|e| panic!("move {} → {}: {e}", extracted.display(), target.display()));

            let _ = std::fs::remove_file(&tmp_zip);
            let _ = std::fs::remove_dir_all(&tmp_extract);
        }

        // SPM's binary-target plumbing wires the framework into the Swift
        // compile invocation (helped by the unsafeFlags in Package.swift),
        // but it does NOT propagate to the final Rust → cc link step that
        // cargo drives. Without these directives we get "framework not
        // found" + undefined `_OBJC_CLASS_$_LevelPlay` style symbols at
        // the very last link.
        let basename = xcframework_name.trim_end_matches(".xcframework");
        let search = target.join(slice);
        println!("cargo:rustc-link-search=framework={}", search.display());
        println!("cargo:rustc-link-lib=framework={basename}");
    }
}
